/**
 * Test setup file for AutoTypeScript instrumentation
 * This file loads the instrumentation setup before tests run
 */

// Note: The actual instrumentation setup file will be generated by AutoTypeScript
// at .autotypescript/setup.js in the project root.
// For manual testing, we can create a minimal setup here.

console.log('[Test Setup] Sample TypeScript project test setup loaded');
